<a href="https://colab.research.google.com/github/DarshilTheCoder/PyTorch_Learnings/blob/main/Pytorch_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

## **Tensors**

In [4]:
tensor_2d = torch.randn(3,4)
tensor_2d

tensor([[-0.2054,  0.8494, -0.6587,  0.9660],
        [-0.0794,  0.0388,  0.7237, -0.2344],
        [ 0.0312,  0.9037,  0.3216, -0.8581]])

In [5]:
tensor_3d = torch.randn(2,3,4)
tensor_3d
#Here in 3d, first list and second list is the rows (i.e row1 and row2). Now each list have some rows that are actual columns. And the columns are actually the z-axis. Because it is in 3-Dimension

tensor([[[-0.6594,  1.2984, -0.6813,  0.5414],
         [-0.3579,  0.1392, -1.4665, -0.4593],
         [ 0.4306,  0.9349,  2.7710, -0.8545]],

        [[ 1.4350,  1.2339, -0.3869,  0.7614],
         [-0.1524,  1.3084, -0.8228,  1.5541],
         [ 0.5366, -0.1311, -0.2357,  0.1132]]])

In [7]:
tensor_4d = torch.randn(2,3,4,5)
tensor_4d

tensor([[[[-1.5640, -1.8542,  1.3792, -0.0651,  1.0897],
          [ 1.2446,  0.9617, -0.5158, -0.5467,  2.1333],
          [-1.0479,  0.0983, -0.3245, -1.1521, -0.5652],
          [ 0.5753,  0.7158, -0.4695,  0.8185,  0.9417]],

         [[ 0.9757, -1.3130, -2.4560,  1.2659, -0.0090],
          [-0.1764, -1.4837, -0.6471, -0.8389, -1.3356],
          [ 0.1931,  0.1586, -0.6029,  0.7264,  0.0567],
          [ 1.0053,  0.2486,  0.6552,  0.3036, -0.4736]],

         [[ 1.0625,  1.2717,  0.7956,  1.7219, -0.1034],
          [ 0.3032, -0.5799, -0.2400,  0.2404,  0.4823],
          [ 0.1445, -1.2671, -0.4641,  1.7949,  0.2871],
          [-1.1410,  0.3314, -0.0030, -0.2430,  0.1712]]],


        [[[-0.6245,  0.0719,  1.2607,  0.4180, -0.4688],
          [-0.3518, -0.2620,  0.8203, -0.1667,  1.1043],
          [ 1.4737, -1.4122, -0.2474,  0.1710,  1.3051],
          [ 0.1294,  0.4471,  0.7207, -0.4210,  1.3793]],

         [[-0.4452, -0.6918,  0.1529, -1.2437,  1.1004],
          [-1.3443,  

#Tensors Basic Operations


In [18]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Reshape() and View()

In [19]:
#You can reshape it using reshape() and view
my_torch2 = my_torch.reshape(2,5)
my_torch2

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [20]:
#If you don't know how many numbers are there then you can use -1 in that case
my_torch3 = my_torch.reshape(2,-1)
my_torch3

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [27]:
my_torch4 =my_torch.view(5,2)
my_torch4

tensor([[  0, 102],
        [  2,   3],
        [  4,   5],
        [  6,   7],
        [  8,   9]])

In [24]:
#Things to note here in tensor is that if you made any changes into the original one then that changes will get refleted others. For example

my_torch[1] = 102
my_torch

tensor([  0, 102,   2,   3,   4,   5,   6,   7,   8,   9])

In [26]:
#Now checking the torch2
my_torch2 #see 1 get's changed to 102

tensor([[  0, 102,   2,   3,   4],
        [  5,   6,   7,   8,   9]])

## Slics
*It is used to grab a specific section of the tensor*

In [33]:
my_torch5 = my_torch4[:,1:]
my_torch5

tensor([[102],
        [  3],
        [  5],
        [  7],
        [  9]])

In [37]:
my_torch6 = tensor_3d[:,1:]
my_torch6

tensor([[[-0.3579,  0.1392, -1.4665, -0.4593],
         [ 0.4306,  0.9349,  2.7710, -0.8545]],

        [[-0.1524,  1.3084, -0.8228,  1.5541],
         [ 0.5366, -0.1311, -0.2357,  0.1132]]])

# Tensor Maths Operation

In [72]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])

print(tensor_a,tensor_b)

tensor([1, 2, 3, 4]) tensor([5, 6, 7, 8])


In [55]:
#Addition
print(tensor_a+tensor_b)
#or
#torch.add(tensor_a,tensor_b)
#or
tensor_a.add(tensor_b)

tensor([ 6,  8, 10, 12])


tensor([ 6,  8, 10, 12])

In [43]:
#Subtraction
print(tensor_a-tensor_b)
#OR
torch.sub(tensor_a,tensor_b)

tensor([-4, -4, -4, -4])


tensor([-4, -4, -4, -4])

In [45]:
#Multiplication
print(tensor_a*tensor_b)
#or
torch.mul(tensor_a,tensor_b)

tensor([ 5, 12, 21, 32])


tensor([ 5, 12, 21, 32])

In [49]:
#Division
print((tensor_a/tensor_b))
#or
torch.div(tensor_a,tensor_b)

tensor([0.2000, 0.3333, 0.4286, 0.5000])


tensor([0.2000, 0.3333, 0.4286, 0.5000])

In [52]:
#Remainders
print(tensor_a % tensor_b)
print(tensor_b % tensor_a)
#or
torch.remainder(tensor_b,tensor_a)

tensor([1, 2, 3, 4])
tensor([0, 0, 1, 0])


tensor([0, 0, 1, 0])

In [75]:
#Reassingment
tensor_c = tensor_a + tensor_b
print(tensor_c)
#or
print(tensor_a-tensor_b)
tensor_a.add_(tensor_a-tensor_b) #what here is happening is that 1+(1-5=-4) so 1-4=-3 is assigning to tensor_a and that's why getting -3, similarly for second one 2-6=-4 and 2-4 = -2.
tensor_a

tensor([ 6,  8, 10, 12])
tensor([-4, -4, -4, -4])


tensor([-3, -2, -1,  0])

In [69]:
tensor_a

tensor([-3, -2, -1,  0])